### ISSUE TITLE
Add an animation to the column actions menu

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1039]
Inspired by the animation on some of GitHub's dropdown menus:

https://github.com/primer/css/blob/da8ee54248e6d76c15c18e53684a15a6516b5b7f/src/utilities/animations.scss#L114-L131

```css
/* Fade in an element and scale it fast */
.anim-scale-in {
  animation-name: scale-in;
  animation-duration: 0.15s;
  animation-timing-function: cubic-bezier(0.2, 0, 0.13, 1.5);
}

@keyframes scale-in {
  0% {
    opacity: 0;
    transform: scale(0.5);
  }

  100% {
    opacity: 1;
    transform: scale(1);
  }
}
```
