### ISSUE TITLE
Column action menu overlapped by Leaflet maps

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1052]
Using `datasette-leaflet-geojson`:

<img width="913" alt="Cursor_and_benches__benches__17_387_rows" src="https://user-images.githubusercontent.com/9599/97127361-a4f1ad80-16f6-11eb-9c81-91ba7c990982.png">

**Comment by simonw** [comment]
The default z-index values for Leaflet are defined here: https://github.com/Leaflet/Leaflet/blob/b346bb8bf7bb80899baa1f4fc1536bae58e7e3e6/dist/leaflet.css#L81-L91

```css
.leaflet-pane         { z-index: 400; }

.leaflet-tile-pane    { z-index: 200; }
.leaflet-overlay-pane { z-index: 400; }
.leaflet-shadow-pane  { z-index: 500; }
.leaflet-marker-pane  { z-index: 600; }
.leaflet-tooltip-pane   { z-index: 650; }
.leaflet-popup-pane   { z-index: 700; }

.leaflet-map-pane canvas { z-index: 100; }
.leaflet-map-pane svg    { z-index: 200; }
```
So a `z-index` of 1000 on the menu should fix this.
