### ISSUE TITLE
Fix footer to the bottom of the page

### ISSUE THREAD

**Issue by abdusco** [simonw/datasette#1129]
Footer doesn't stick to the bottom when the body content isn't enough to reach the bottom.
This could be fixed using flexbox.

![New Project](https://user-images.githubusercontent.com/3243482/101134101-edb45480-361a-11eb-920f-310344afbdd0.png)

```css
body {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.content {
  flex-grow: 1;
}
```
