### ISSUE TITLE
Adopt Prettier for JavaScript code formatting

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1166]
https://prettier.io/ - I'm going to go with 2 spaces.

**Comment by simonw** [comment]
I want a CI check that confirms that files conform to prettier - but only `datasette/static/*.js` files that are not already  minified.

This seems to do the job:

    npx prettier --check 'datasette/static/*[!.min].js'

**Comment by simonw** [comment]
This action looks good - tag 3.2 is equivalent to this commit hash: https://github.com/creyD/prettier_action/tree/bb361e2979cff283ca7684908deac8f95400e779

**Comment by simonw** [comment]
Maybe not that action actually - I wanted to use a pre-built action to avoid installing Prettier every time, but that's what it seems to do: https://github.com/creyD/prettier_action/blob/bb361e2979cff283ca7684908deac8f95400e779/entrypoint.sh#L28-L37

**Comment by simonw** [comment]
I think this should work:
```
- uses: actions/cache@v2
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFiles('**/prettier.yml' }}
```
I'll use the `prettier.yml` workflow that I'm about to create as the cache key for the NPM cache.
