### ISSUE TITLE
Ability to default to hiding the SQL for a canned query

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1422]
I'm working on a project with some HUGE (400+ lines of SQL) canned queries right now.

Any time you land on the canned query page you have to scroll down a long distance to get to the results!

Would be useful to be able to default to https://latest.datasette.io/fixtures/magic_parameters?_hide_sql=1 without needing the parameter.

**Comment by simonw** [comment]
If you do this it should still be possible to view the SQL - which means we need a new parameter. I propose `?_show_sql=1` to over-ride the hidden default.

I think the configuration should look like this:
```yaml
databases:
  fixtures:
    queries:
      neighborhood_search:
        hide_sql: true
        sql: |-
          select neighborhood, facet_cities.name, state
          from facetable
            join facet_cities on facetable.city_id = facet_cities.id
          where neighborhood like '%' || :text || '%'
          order by neighborhood
        title: Search neighborhoods
```
