### ISSUE TITLE
Modify base.html template to support optional sticky footer

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1446]
The neatest way to have the footer stick to the bottom of the browser window that I've found is to use the flexbox pattern from https://css-tricks.com/couple-takes-sticky-footer/

```html
<body>
  <div class="content">
    content
  </div>
  <footer class="footer"></footer>
</body>
```
```css
html, body {
  height: 100%;
}
body {
  display: flex;
  flex-direction: column;
}
.content {
  flex: 1 0 auto;
}
.footer {
  flex-shrink: 0;
}
```
I tried this in a custom plugin but it ended up having to duplicate the entire `base.html` template just to get a wrapper around the not-footer content.

I think Datasette's own `base.html` template should have this wrapper element instead.

**Comment by simonw** [comment]
OK, now the following optional CSS gives us a sticky footer:
```css
html, body {
  height: 100%;
}
body {
  display: flex;
  flex-direction: column;
}
.not-footer {
  flex: 1 0 auto;
}
footer {
  flex-shrink: 0;
}
```
