### ISSUE TITLE
Potential simplified publishing mechanism

### ISSUE THREAD

**Issue by aidansteele** [simonw/datasette#1615]
Hi,

Forewarning: this idea is one I've only been thinking about for a while and it's not fully fleshed-out yet.

I love Datasette and what it stands for. I was thinking about how we could make it accessible to more people, especially those without access to credit cards required for a lot of hosting options. Or they might not feel comfortable signing up for said services.

So I was thinking I might create a service that hosts Datasette instances for folks. I'd probably stick it on AWS Lambda and limit requests to something like n/month to avoid bankrupting myself. If I did build such a hypothetical service, I was thinking I would rely on GitHub Actions to do the heavy lifting. 

E.g. user `johndoe` creates a repo `my-animals` with a couple of files: `dogs.csv`, `cats.csv` and the following GitHub Actions workflow:

```yaml
# .github/workflows/push.yml
on:
  push

# this allows the publish action to use OIDC to authenticate johndoe/my-animals
permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2

      - run: pip install sqlite-utils

      - uses: actions/checkout@v2

      - run: |
          set -eux
          
          sqlite-utils create-database animals.db          
          sqlite-utils insert animals.db dogs dogs.csv --csv          
          sqlite-utils insert animals.db cats cats.csv --csv

      - uses: datasette-hub/publish@v1
        with:
          db: animals.db
          metadata: meta.yml

        # this step is helpful for debugging why the
        # generated sqlite db was rejected
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: animals.db
          retention-days: 1
```

This would then cause a Datasette instance to be available at `https://johndoe-my-animals.datasette-hub.test/`. It feels like this could significantly reduce the friction to someone being able to go from data set to Datasette.

What do you think? Does this address a real need? Or am I perhaps misunderstanding the main friction points? As a bonus: it feels like this would pair well with [git scraping](https://simonwillison.net/2020/Oct/9/git-scraping/).
