### ISSUE TITLE
Baked in way of configuring arbitrary permissions in metadata

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1636]
The `"allow"` block mechanism can already be used to configure various default permissions. When adding permissions to `datasette-tiddlywiki` I realized it would be good to be able to configure arbitrary permissions such as `edit-tiddlywiki` there too.

**Comment by simonw** [comment]
I keep running I to a need for this. Every time I create a new plugin that defines a new permission I wish there was a clean way to grant that permission to new users without installing some other permissions plugin.

**Comment by simonw** [comment]
I keep shipping plugins that set a special hook just so the root user can try them out.

**Comment by simonw** [comment]
Current design:

```json
{
    "databases": {
        "private": {
            "allow": {
                "id": "*"
            }
        }
    }
}
```
This can be applied at the instance, database, table or query level within the nested JSON.

https://docs.datasette.io/en/stable/authentication.html#controlling-access-to-specific-databases

It's actually controlling the following permissions:

- `view-instance`
- `view-database`
- `view-table`
- `view-query`

**Comment by simonw** [comment]
So the new mechanism needs to extend that to handle all of the other permissions as well.

The simplest design I can think of is this (here illustrated using YAML):

```yaml
# instance-level permissions - give everyone the debug menu:
permissions:
  debug-menu:
    id: *
databases:
  content:
    # Allow bob to create-table in the content database
    permissions:
      create-table:
        id: bob
```
