### ISSUE TITLE
Update screenshots in documentation to match latest designs

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1844]
https://docs.datasette.io/en/0.62/full_text_search.html has this out-of-date screenshot:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/9599/195911747-386f4cd2-5239-4c83-8e0c-072e6ae56ff6.png">

**Comment by simonw** [comment]
I just spotted some other out-dated screenshots in the `docs/` directory:

- [advanced_export.png](https://github.com/simonw/datasette/blob/main/docs/advanced_export.png "advanced_export.png")
- [binary_data.png](https://github.com/simonw/datasette/blob/main/docs/binary_data.png "binary_data.png")
- [facets.png](https://github.com/simonw/datasette/blob/main/docs/facets.png "facets.png")
- [full_text_search.png](https://github.com/simonw/datasette/blob/main/docs/full_text_search.png "full_text_search.png")

**Comment by simonw** [comment]
For the advanced export one:

    shot-scraper 'https://latest.datasette.io/fixtures/facetable' -s '#export' -p 10

Produces:

![latest-datasette-io-fixtures-facetable](https://user-images.githubusercontent.com/9599/195913105-02abdb38-49ed-4077-ad99-cb98f98ee818.png)

**Comment by simonw** [comment]
For this image:

<img src="https://github.com/simonw/datasette/blob/79aa0de083d38a9975915d5a4cc68ca6c74fbe3d/docs/binary_data.png?raw=true">

https://latest.datasette.io/fixtures/binary_data has an extra row these days:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/9599/195914820-b3f7d820-e229-4668-bf90-a4f3d0e95e79.png">

This deletes every row past the first two (first three including the header row):
```javascipt
Array.from(document.querySelectorAll('tr:nth-child(n+3)'), el => el.parentNode.removeChild(el));
```

**Comment by simonw** [comment]
So:
```
shot-scraper 'https://latest.datasette.io/fixtures/binary_data' \
  -j "Array.from(document.querySelectorAll('tr:nth-child(n+3)'), el => el.parentNode.removeChild(el));" \
  -s table -p 10
```
![latest-datasette-io-fixtures-binary_data 1](https://user-images.githubusercontent.com/9599/195915092-be81db43-5672-4375-bd66-4316211b1afc.png)

**Comment by simonw** [comment]
Here's the new advanced export image:

<img src="https://github.com/simonw/datasette-screenshots/blob/1fc70adc3f20ee19cadff21653718d5f1a7bcb1f/advanced-export.png?raw=true">

**Comment by simonw** [comment]
I'm going to use this page for the facets screenshot: https://congress-legislators.datasettes.com/legislators/legislator_terms?_facet=type&_facet=party&_facet=state&_facet_size=10

Trying for this bit:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/9599/195916927-74636861-c02b-4744-bfac-68e0b6147b48.png">

**Comment by simonw** [comment]
This seems to get every table cell in that table for the first 3 rows and the columns up to `party`:

    document.querySelectorAll('tr:not(:nth-child(n+4)) td:not(:nth-child(n+10)')

**Comment by simonw** [comment]
This works:
```
shot-scraper
  'https://congress-legislators.datasettes.com/legislators/legislator_terms?_facet=type&_facet=party&_facet=state&_facet_size=10' \
  -s '.suggested-facets a' \
  --selector-all 'tr:not(tr:nth-child(n+4)) td:not(:nth-child(n+11))' \
  -p 10
```
![congress-legislators-datasettes-com-legislators-legislator_terms 6](https://user-images.githubusercontent.com/9599/195919422-97616694-3ec0-4e05-afc2-c509275c767c.png)

**Comment by simonw** [comment]
I'm going to link the documentation screenshots directly to the images in the https://github.com/simonw/datasette-screenshots repository - but I don't want those images to reflect `main` when the documentation may reflect a specific version.

So I'm going to start tagging releases of `datasette-screenshots` so I can get permanent URLs to those images.

**Comment by simonw** [comment]
That's the last two screenshots:

<img src="https://raw.githubusercontent.com/simonw/datasette-screenshots/1b56cd4177089b72de9436749a8995921fe8e870/non-retina/binary-data.png">

<img src="https://raw.githubusercontent.com/simonw/datasette-screenshots/1b56cd4177089b72de9436749a8995921fe8e870/non-retina/faceting-details.png">

**Comment by simonw** [comment]
I'm going to tag `datasette-screenshots` with the current Datasette version, `0.62`.

**Comment by simonw** [comment]
OK, the URLs to use in the docs are:

- https://github.com/simonw/datasette-screenshots/blob/0.62/advanced-export.png?raw=true (retina)
- https://github.com/simonw/datasette-screenshots/blob/0.62/non-retina/regmem-search.png?raw=true
- https://github.com/simonw/datasette-screenshots/blob/0.62/binary-data.png?raw=true
- https://github.com/simonw/datasette-screenshots/blob/0.62/non-retina/faceting-details.png?raw=true

**Comment by simonw** [comment]
New images are now live on these pages:
- https://docs.datasette.io/en/latest/csv_export.html
- https://docs.datasette.io/en/latest/binary_data.html
- https://docs.datasette.io/en/latest/facets.html
- https://docs.datasette.io/en/latest/full_text_search.html
- https://docs.datasette.io/en/latest/changelog.html#v0-23 (was a duplicate of the advanced export image)

**Comment by simonw** [comment]
Here's the YAML I added to https://github.com/simonw/datasette-screenshots/blob/main/shots.yml for this issue:

```yaml
- url: https://register-of-members-interests.datasettes.com/regmem/items?_search=hamper&_sort_desc=date
  height: 585
  width: 960
  output: regmem-search.png
- url: https://register-of-members-interests.datasettes.com/regmem/items?_search=hamper
  selector: "#export"
  output: advanced-export.png
  padding: 10
- url: https://congress-legislators.datasettes.com/legislators/legislator_terms?_facet=type&_facet=party&_facet=state&_facet_size=10
  selectors_all:
  - .suggested-facets a
  - tr:not(tr:nth-child(n+4)) td:not(:nth-child(n+11))
  padding: 10
  output: faceting-details.png
- url: https://latest.datasette.io/fixtures/binary_data
  selector: table
  javascript: |-
    Array.from(
      document.querySelectorAll('tr:nth-child(n+3)'),
      el => el.parentNode.removeChild(el)
    );
  padding: 10
  output: binary-data.png
```
