### ISSUE TITLE
Allow to hide some queries in metadata.yml

### ISSUE THREAD

**Issue by CharlesNepote** [simonw/datasette#1968]
By default all queries are displayed.

But there are many cases where it would be interesting to hide the queries by default:
* the website is targeting non-tech people
* the query is veeeeeery long ([eg.](https://mirabelle.openfoodfacts.org/products/energy_calculator))
* reading the query is not important for the users, they only want to see the result

Of course, the user still could have the option to see the query.

It could be an option in the metadata file:
```yml
databases:
  awesome_db:
    tables:
      products:
        hide_sql: true
    queries:
      great_query:
        hide_sql: true
        sql: select * from products where code = :barcode
```

The priority could be:
* no option in the metadata and nothing in the URL: query displayed
* hide_sql in the metadata and nothing in the URL: query displayed as asked in the metadata
* hide_sql in the metadata and &_hide_sql= in the URL: query as asked in the URL

See also: #1824
