### ISSUE TITLE
"Cannot sort table by id" when sortable_columns is used

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#1980]
I had an instance with this in `metadata.yml`:

```yaml
databases:
  timezones:
    tables:
      timezones:
        sortable_columns:
        - tzid
```
When I clicked on the "Apply" button here:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/9599/211236149-6c85eca9-5200-440a-9bc8-a913cd8164f5.png">

It sent me to `/timezones/timezones?_sort=id&id__exact=133` with the error message:

> 500: Cannot sort table by id
