### ISSUE TITLE
on_success_message_sql option for writable canned queries

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2138]
> Or... how about if the `on_success_message` option could define a SQL query to be executed to generate that message? Maybe `on_success_message_sql`.

- https://github.com/simonw/datasette/issues/2134

**Comment by simonw** [comment]
Goal here is to customize the message displayed after a query has succeeded. e.g.

```yaml
databases:
  mydatabase:
    queries:
      add_name:
        sql: INSERT INTO names (name) VALUES (:name)
        write: true
        on_success_message_sql: 'select ''Name inserted: '' || :name'
        on_success_redirect: /mydatabase/names
```
