### ISSUE TITLE
Table configuration settings should work in both metadata.yml and datasette.yml

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2247]
The https://docs.datasette.io/en/latest/configuration.html page should gather together the various table settings, including:

https://docs.datasette.io/en/latest/facets.html#facets-in-metadata

```yaml
databases:
  sf-trees:
    tables:
      Street_Tree_List:
        facets:
        - qLegalStatus
        facet_size: 10
```

https://docs.datasette.io/en/latest/full_text_search.html#configuring-full-text-search-for-a-table-or-view

```yaml
databases:
  russian-ads:
    tables:
      display_ads:
        fts_table: ads_fts
        fts_pk: id
        searchmode: raw
```

And a bunch of stuff from metadata (has this moved to `datasette.yaml` yet?)

https://docs.datasette.io/en/latest/metadata.html#setting-a-default-sort-order

```yaml
databases:
  mydatabase:
    tables:
      example_table:
        sort_desc: created
        size: 10
        sortable_columns:
        - height
        - weight
        label_column: title
        hidden: true
```
There's a full list here:

https://docs.datasette.io/en/latest/metadata.html#table-level-metadata

- [ ] `hidden`
- [ ] `sort/sort_desc`
- [ ] `size`
- [ ] `sortable_columns`
- [ ] `label_column`
- [ ] `facets`
- [ ] `fts_table`
- [ ] `fts_pk`
- [ ] `searchmode`
