### ISSUE TITLE
Permissions defined in datasette.yml do not correctly obey the veto rule

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2292]
https://docs.datasette.io/en/1.0a12/authentication.html#other-permissions-in-datasette-yaml describes how you can nest permissions in `datasette.yml` something like this:
```
databases:
  docs:
    permissions:
      update-row:
        id: editor
    tables:
      news:
        update-low:
          false
```
One would expect the above to allow `editor` to update row in any table in `docs` except for `news` - since that would fit the veto rule described in https://docs.datasette.io/en/1.0a12/authentication.html#how-permissions-are-resolved

But that's not actually what happens - in the above case (or a case like it) - as far as I can tell the database-level rule is obeyed and the table-level one is ignored.

I was testing this with:
```bash
datasette content.db --secret 1  \
  -s plugins.datasette-unsafe-actor-debug.enabled 1 \
  -s databases.content.tables.news.permissions.update-row false \
  -s databases.content.permissions.update-row true \
  --reload
```
