### ISSUE TITLE
Add a bit of a gradient to the header and maybe the footer

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2302]
Currently looks like this: 

![CleanShot 2024-03-12 at 16 50 59@2x](https://github.com/simonw/datasette/assets/9599/15ea7809-33c0-4087-bea6-cf904bebfca0)

I've been trying this out on Datasette Cloud for a while and I like it:

![CleanShot 2024-03-12 at 16 51 29@2x](https://github.com/simonw/datasette/assets/9599/65ad6c99-d361-4069-b2a2-83f67f03e025)

**Comment by simonw** [comment]
Here's the CSS I added to Datasette Cloud to get this:

```css
body header {
    background: linear-gradient(180deg, rgba(96,144,173,1) 0%, rgba(39,104,144,1) 50%); 
}
body .nav-menu-inner li {
    padding: 0.3rem 0.5rem;
    border-top: 1px solid #ffffff69;
}
body details .nav-menu-inner {
    top: 2.6rem;
    padding: 0;
}
```
