### ISSUE TITLE
Better wrapping of breadcrumbs when user is logged in

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#2304]
I had this custom CSS on Datasette Cloud:
```css
header p.crumbs {
    padding-right: 2em;
}
```
Should probably be added to Datasette core, following:
- #2302
