### ISSUE TITLE
Validate metadata.json on startup

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#260]
It's easy to misspell the name of a database or table and then be puzzled when the metadata settings silently fail.

To avoid this, let's sanity check the provided metadata.json on startup and quit with a useful error message if we find any obvious mistakes.

**Comment by simonw** [comment]
This came up in #588 - it would be helpful if this would spot things like `"queries"` defined against the tables block when they should be defined against a database.

**Comment by simonw** [comment]
Interesting example of why this would be valuable here:
- https://github.com/simonw/datasette/issues/1798

This YAML file:
```yaml
title: Some title
description_html: |-
  <p>This is an experiment.</p>
databases:
  off:
    tables:
      products_from_owners:
        title: products_from_owners*
```
Was loaded as equivalent to this JSON:
```json
{
    "title": "Some title",
    "description_html": "<p>This is an experiment.</p>",
    "databases": {
        "false": {
            "tables": {
                "products_from_owners": {
                    "title": "products_from_owners*"
                }
             }
        }
    }
}
```
Validation would have caught this.
