### ISSUE TITLE
Search box CSS doesn't look great on OS X Safari

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#701]
<img width="1447" alt="twitter__tweets__68_773_rows_where_sorted_by_id_descending_and_twitter__tweets__955_rows" src="https://user-images.githubusercontent.com/9599/77002262-73bb2e80-6918-11ea-87a3-e3f537365c9f.png">

**Comment by simonw** [comment]
https://css-tricks.com/webkit-html5-search-inputs/ talks about this.

**Comment by simonw** [comment]
It looks like the problem is that the `padding: 9px 4px` rule is being ignored.

**Comment by simonw** [comment]
From the comments on that css-tricks article, this appears to work:
```css
input[type=search] {
    -webkit-appearance: textfield;
}
input[type="search"]::-webkit-search-decoration,
input[type="search"]::-webkit-search-cancel-button,
input[type="search"]::-webkit-search-results-button,
input[type="search"]::-webkit-search-results-decoration {
    display: none;
}
```
