### ISSUE TITLE
Writable canned queries live demo

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#805]

**Comment by simonw** [comment]
I'd like to illustrate writable canned queries without the risk of someone abusing and breaking it (or filling it with bad content).

I don't want to have to monitor it, so an application that won't run out of disk space after a few months would be good too.

Maybe a polling app? If I'm only tracking integer numbers of votes it shouldn't ever run out of space.

**Comment by simonw** [comment]
Would be useful if I had a plugin that could authenticate users based on a secret environment variable (maybe for a password) - that way I could have an "admin" account on the Glitch app that is allowed to setup new polls, while anonymous users can only vote on them.

**Comment by simonw** [comment]
Part of #806

**Comment by simonw** [comment]
Create `data.db` with:
```
echo '{"emoji": "🐯", "score": 0}' | sqlite-utils insert data.db emojis --pk=emoji -
echo '{"emoji": "🐺", "score": 0}' | sqlite-utils insert data.db emojis --pk=emoji -
```
Then run Datasette with this `metadata.yaml`:
```yaml
title: Datasette Poll
databases:
  data:
    queries:
      vote:
        sql: |-
          update emojis set score = score + 1 where emoji = :emoji
        write: true
```
