### ISSUE TITLE
"latest" in new documentation navbar is invisible

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#892]
On https://datasette.readthedocs.io/en/latest/

<img width="572" alt="Datasette_—_Datasette_documentation" src="https://user-images.githubusercontent.com/9599/87255376-1b67e980-c43f-11ea-8470-781ee8842336.png">

Compare with https://datasette.readthedocs.io/en/0.45/

<img width="584" alt="Datasette_—_Datasette_documentation" src="https://user-images.githubusercontent.com/9599/87255387-2fabe680-c43f-11ea-875e-c474364691ca.png">

Some custom CSS should fix it.

**Comment by simonw** [comment]
```css
.wy-side-nav-search > div.version {
    margin-top: -.4045em;
    margin-bottom: .809em;
    font-weight: normal;
    color: rgba(255,255,255,0.3);
}
```
Fix can go here: https://github.com/simonw/datasette/blob/ee0ef016523a765b6ef6eaa43cad9ad568f78ae4/docs/_static/css/custom.css#L1-L3
