### ISSUE TITLE
Private/secret databases: database files that are only visible to plugins

### ISSUE THREAD

**Issue by simonw** [simonw/datasette#950]
In thinking about the best way to implement https://github.com/simonw/datasette-auth-passwords/issues/6 (SQL-backed user accounts for `datasette-auth-passwords`) I realized that there are a few different use-cases where a plugin might want to store data that isn't visible to regular Datasette users:

- Storing password hashes
- Storing API tokens
- Storing secrets that are used for data import integrations (secrets for talking to the Twitter API for example)

Idea: allow one or more private database files to be attached to Datasette, something like this:

    datasette github.db linkedin.db -s secrets.db -m metadata.yml

The `secrets.db` file would not be visible using any of the Datasette's usual interface or API routes - but plugins would be able to run queries against it.

So `datasette-auth-passwords` might then be configured like this:

```yaml
plugins:
  datasette-auth-passwords:
    database: secrets
    sql: "select password_hash from passwords where username = :username"
```
The plugin could even refuse to operate against a database that hadn't been loaded as a secret database.
